#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if dpkg --compare-versions "$2" lt-nl "4.9.0-1~deb8u1pexip2"; then
	rm -f "/etc/apparmor.d/disable/usr.sbin.tcpdump" || true
	rm -f "/etc/apparmor.d/force-complain/usr.sbin.tcpdump" || true
	rm -f "/etc/apparmor.d/local/usr.sbin.tcpdump" || true
	rmdir /etc/apparmor.d/local 2>/dev/null || true
    fi
fi

#DEBHELPER#
